name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        otp-version: [22, 23]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        allow-cache: [true, false]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: bajankristof/setup-erlang@master
      with:
        otp-version: ${{ matrix.otp-version }}
        allow-cache: ${{ matrix.allow-cache }}
    - run: erl -version
    - run: rebar3 version
